kumuluzee:
  name: polnilne-postaje
  version: 1.0.0
  env:
    name: dev
  #PODATKOVNA BAZA
  datasources:
    - jndi-name: jdbc/polnilnePostaje
      connection-url: jdbc:postgresql://host.docker.internal:5432/polnilnePostaje
      username: postgres
      password: postgres