kumuluzee:
  name: polnilne-postaje
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/polnilnePostaje
    connection-url: jdbc:postgresql://localhost:5432/polnilnePostaje
    username: postgres
    password: postgres
  security:
    keycloak:
      json: '{"realm": "uporabnik-realm",
            "bearer-only": true,
            "auth-server-url": "http://localhost:8083/auth/",
            "ssl-required": "external",
            "resource": "uporabnik-api",
            "confidential-port": 0}'