kumuluzee:
  name: polnilne-postaje
  version: 1.0.0
  env:
    name: dev
  datasources:
  - jndi-name: jdbc/polnilnePostaje
    connection-url: jdbc:postgresql://host.docker.internal:5432/polnilnePostaje
    username: postgres
    password: postgres
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
      data-source-health-check:
        connection-url: jdbc:postgresql://host.docker.internal:5432/polnilnePostaje
        username: postgres
        password: postgres
  security:
    keycloak:
      json: '{"realm": "uporabnik-realm",
            "bearer-only": true,
            "auth-server-url": "http://localhost:8083/auth/",
            "ssl-required": "external",
            "resource": "uporabnik-api",
            "confidential-port": 0}'
integrations:
  novice:
    base-url: http://localhost:8082/v1